name: Deploy to Beanstalk
on: 
  push:
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps: 
      - uses: actions/checkout@master
        name: Setup JDK 17
      - uses: actions/setup-java@v4.7.0
        with: 
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4.6.2
        
  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps: 
      - name: Download JAR
        uses: actions/download-artifact@v4.2.1
        with: 
          name: artifact

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with: 
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY}}
          application_name: evagas
          environment_name: Evagas-env
          version_label: ${{ github.SHA }}
          region: us-east-1
          deployment-package: evagas-0.0.1-SNAPSHOT.jar
    
