name: Deploy Beanstalk
on: 
  push:
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps: 
      - uses: actions/checkout@master
        name: Setup JDK 17
      - uses: actions/setup-java@v4.7.0
        with: 
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with: 
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY}}
          application_name: evagas
          environment_name: Evagas-env
          version_label: ${{ github.SHA }}
          region: us-east-1
          deployment_package: target/evagas-0.0.1-SNAPSHOT.jar

     
    
